<html>
    <?php include PACKAGES . "admin/views/head.phtml"; ?>
    <body>

        <?php include PACKAGES . "admin/views/header.phtml"; ?>
        <a href = "/">&lt;&lt;Back to the site</a>
        <h1>Login page</h1>
        <form action="/admin/login" method="POST">
            User: <input name="user">
            Pass: <input type="password" name="pass">
            <input type="submit" name="send" value="Login">
        </form>
    </body>
</html>