<?php include "../app/site/views/header.html"; ?>

<style>
    tr.highlight:hover {
        background: yellow;
    }
</style>

<a href = "/">Home</a> | <a href = "/tests">Tests</a> | <a href = "/admin">Administration</a>

<h1>Tests</h1>

<h2>Testing matches between ways and patterns</h2>
<table border="1" cellspacing="0" cellpadding="5" width="100%">
    <tr>
        <th></th>
        <th width="20%">Pattern</th>
        <th width="20%">Way</th>
        <th width="20%">Match</th>
        <th>Args</th>
    </tr>

	<?php foreach($pairs as $title => $pair): ?>

		<?php $pattern = $pair[0]; ?>
		<?php $way = $pair[1]; ?>
		<?php $xargs = []; ?>
		<?php $r = divWays::match($pattern, $way, $xargs); ?>

        <tr class="highlight">
            <td><?php echo $title; ?></td>
            <td><?php echo $pattern; ?></td>
            <td><?php echo $way; ?></td>
            <td><?php echo $r ? "TRUE" : "FALSE" ?></td>
            <td>
				<?php foreach($xargs as $xarg => $value): ?>
                    <b><?php echo $xarg; ?></b> = <?php echo $value; ?>
				<?php endforeach; ?>
            </td>
        </tr>

	<?php endforeach; ?>
</table>